export const pricingData = [
    {
        title: "Migrations",
        subtitle: "Starting at",
        price: "$1,950",
        period: "Annual Subscription",
        features: [
            "Data Migration",
            "Simple Tax Preparation",
            "Fund Administration",
            "Fund Manager",
            "Investor Records",
        ],
        buttonText: "Get Price Estimate",
        buttonId: "button1",
        buttonColor: "brand",
    },
    {
        title: "SPVS",
        subtitle: "Starting at",
        price: "$9,950",
        period: "Setup Cost",
        features: [
            "Series of Entity Included",
            "Bank Account",
            "Investor Onboarding",
            "Fund Manager",
            "Regulatory Filings",
            "Simple Tax Preparation",
        ],
        buttonText: "Get Price Estimate",
        buttonId: "button2",
        buttonColor: "brand",
    },
    {
        title: "Funds",
        subtitle: "Starting at",
        price: "$19,500",
        period: "Annual Subscription",
        features: [
            "30 Investments Included",
            "18 Month Raising Period",
            "36 Month Investing Period",
            "Annual Financial Statements",
            "Multiple Closes Supported",
        ],
        buttonText: "Get Price Estimate",
        buttonId: "button3",
        buttonColor: "brand",
    },
    {
        title: "Custom Funds",
        subtitle: "Starting at",
        price: "$49,500",
        period: "Annual Subscription",
        features: [
            "Custom Investments",
            "Custom Raising Period",
            "Custom Investment Period",
            "Custom Financial Statements",
            "Custom Classes",
        ],
        buttonText: "Get Price Estimate",
        buttonId: "button4",
        buttonColor: "brand",
    },
];